### ISSUE TITLE
/editReview route causes crash

### ISSUE THREAD

**Issue by peteherman** [seanmbills/FFBT-Server-Heroku#29] opened 2019-11-22 20:13 UTC
Hit the edit Review route when testing frontend changes and cause the server to crash.

**Comment by seanmbills** [comment] 2019-11-24 16:42
Not able to reproduce. If no one else can either, I'll go ahead and close.

**Comment by seanmbills** [comment] 2019-11-25 19:38
Closed. Fixed by manually pushing changes to the backend.

**Closed by seanmbills** 2019-11-25 19:38 UTC
Labels: bug
